language: node_js
node_js:
  - '10'

# Travis-CI Caching
cache:
  directories:
    - node_modules

deploy:
  provider: pages
  local_dir: dist/
  skip_cleanup: true
  github_token: $CODECOV_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: master

# S:Build Lifecycle
install:
  - npm install

script:
  - npm run build
  - npm run test

after_success:
  - npm run coverage